### ISSUE TITLE
[BUG] - execution failed

### ISSUE THREAD

**Issue by b4b857f6ee** [hlldz/dazzleUP#1]
Hello,

I'm not a dev guru so be nice .

I just compile it with visual studio 2019

On my local workstation it's work but at the end i have this (Windows 10 Pro 2004) : 

![image](https://user-images.githubusercontent.com/36012515/88263386-44536e80-ccca-11ea-9414-bf8217117a85.png)

And when i was testing it on a VM Windows 10 PRO 1903 i get this : 

![image](https://user-images.githubusercontent.com/36012515/88265701-43244080-ccce-11ea-9aa8-db7208f6ab41.png)

**Comment by hlldz** [comment]
Hi,

I am not a dev guru too so don't worry ;)

First of all, I commit a bug fix for your first problem. You can get the details from this link; https://github.com/hlldz/dazzleUP/commit/408b0723b6ffb729ed0a4ff048bca854e823ca90

I think it is fine right know. I tested it on two different Windows operating systems with build number value 2004 and 1909 and everything works fine.

For the solution of the problems you mentioned in the last three screenshots, you should select `Multi-threaded Debug (/ MTd)` for Debug release from `Project> dazzleUP Properties> C / C ++> Code Generation> Runtime Library`.

**Comment by b4b857f6ee** [comment]
Perfect! men it's work!
