### ISSUE TITLE
Reference "use dazzleUP directly using standalone .EXE"

### ISSUE THREAD

**Issue by discmixr** [hlldz/dazzleUP#3]
First, Thank-you for your time & expertise!

Not wanting to purchase the cobaltstrike product, I was wondering if the standalone .exe referenced in the"
Operational Usage - 1" illustration will be made available?

Thanks,

Bob

**Comment by Davewarrington** [comment]
https://github.com/hlldz/dazzleUP/releases/tag/v1.0 ?

**Comment by discmixr** [comment]
Thank-You! Somehow I didn't see it despite what I thought was pretty thorough search of the release.
-Bob
