### ISSUE TITLE
Could not find reflective loader 

### ISSUE THREAD

**Issue by rakjong** [hlldz/dazzleUP#4]
![image](https://user-images.githubusercontent.com/38517715/89665882-f5354c80-d90b-11ea-8e94-e83ad6de13e9.png)

**Comment by hlldz** [comment]
Hi,

You need to add `dazzleUP_Reflective_DLL.dll` file to required path.

Also you can find the DLL file from Release section (https://github.com/hlldz/dazzleUP/releases/tag/v1.0) or you can compile.
