### ISSUE TITLE
Crash in W10 Pro x64

### ISSUE THREAD

**Issue by tsherrington** [hlldz/dazzleUP#5]
Every time I run Dazzle, it crashes at "[*] Modifiable binaries saved as Registry AutoRun checking..."

This is the event log entry.
Faulting application name: dazzleUP.x64.exe, version: 0.0.0.0, time stamp: 0x5f194dd8
Faulting module name: dazzleUP.x64.exe, version: 0.0.0.0, time stamp: 0x5f194dd8
Exception code: 0xc0000005
Fault offset: 0x0000000000011907
Faulting process id: 0x3ea8
Faulting application start time: 0x01d676f0bf5eceba
Faulting application path: C:\download\dazzleUP.x64.exe
Faulting module path: C:\download\dazzleUP.x64.exe
Report Id: cd3ee55d-166f-4013-8626-99ba4c5545ed
Faulting package full name: 
Faulting package-relative application ID: 

I'm attaching the output for added information.

[dazzle.log](https://github.com/hlldz/dazzleUP/files/5103146/dazzle.log)

**Comment by hlldz** [comment]
Hi,

I am completely rewriting the project and will publish it when I'm done. Soon.
