### ISSUE TITLE
Stop working error in Windows 10

### ISSUE THREAD

**Issue by evilc0deooo** [hlldz/dazzleUP#6]
![image](https://user-images.githubusercontent.com/36287351/91658464-de44dd00-eafa-11ea-83d2-1a95a65f860c.png)

![image](https://user-images.githubusercontent.com/36287351/91658453-c66d5900-eafa-11ea-893b-7ca0e8508e31.png)

**Comment by evilc0deooo** [comment]
The above problems also appeared in Windows Server 2012

**Comment by ppbibo** [comment]
![image](https://user-images.githubusercontent.com/36287351/91659416-ec4a2c00-eb01-11ea-82fb-bf4ad8f69873.png)

**Comment by hlldz** [comment]
Hi,

I don't know if there is a continuation of the terminal output. DazzleUP uses the Windows Update Agent (WUA) API. This prolem seems to be related to the WUA API. This is a problem I'm facing as well. I had no problem triggering Windows Update checks before running DazzleUP.

For now I will not release a fix for this problem, I am completely rewriting the project and will publish it when I'm done. Soon.
